#!/bin/sh
# https://aur.archlinux.org/packages/1password-cli/
# Getting started
# https://support.1password.com/command-line-getting-started/

# To confirm the key is legit, see this comment by 1Password’s Jeffrey Goldberg:
# https://discussions.agilebits.com/discussion/comment/420654/#Comment_420654
gpg --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
https://aur.archlinux.org/1password-cli.git
