#!/bin/sh
# https://1password.com/downloads/linux/

url=https://aur.archlinux.org/1password.git
curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

./install-aur.sh $url
