#!/bin/sh
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
# By default, the files are all installed to /usr/local/aws-cli, and a
# symbolic link is created in /usr/local/bin

tmp_path="$(mktemp -d)/awscliv2"
mkdir -p "${tmp_path}"
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "${tmp_path}/awscliv2.zip"
cd "${tmp_path}"
unzip awscliv2.zip
sudo ./aws/install
rm -rf "${tmp_path}"
