#!/bin/sh
# https://aur.archlinux.org/packages/brave-bin
url=https://aur.archlinux.org/brave-bin.git

repo="$(mktemp -d)/$(basename $0)"
git clone "${url}" --depth 1 "${repo}"

cd "${repo}"
makepkg -si
rm -rf "${repo}"

