#!/bin/sh
# https://github.com/tridactyl/tridactyl

url="https://aur.archlinux.org/firefox-tridactyl-native.git"

repo="$(mktemp -d)/$(basename $0)"
git clone "${url}" --depth 1 "${repo}"

cd "${repo}"
makepkg -si
rm -rf "${repo}"
