#!/bin/sh
# https://github.com/ryanoasis/nerd-fonts

url="https://aur.archlinux.org/nerd-fonts-complete.git"

repo="$(mktemp -d)/$(basename $0)"
git clone "${url}" --depth 1 "${repo}"

cd "${repo}"
makepkg -si
rm -rf "${repo}"
