#!/bin/sh
# https://aur.archlinux.org/packages/rider/

url="https://aur.archlinux.org/rider.git"

repo="$(mktemp -d)/$(basename $0)"
git clone "${url}" --depth 1 "${repo}"

cd "${repo}"
makepkg -si
rm -rf "${repo}"
