alias explorer='~/.scripts/open_explorer.sh'
alias choco='/c/ProgramData/chocolatey/bin/choco'
alias github='~/.scripts/open_github.sh'
alias github-pr='~/.scripts/github_pr.sh'
alias github-new='~/.scripts/github_new.sh'
alias pipeline='~/.scripts/open_azure_pipelines.sh'
alias pl='~/.scripts/open_azure_pipelines.sh'
alias main='cd ~/Dev/main'
alias chrome='chrome.exe'
alias tc='open_chrome http://teamcity.stockholm.cint.com:8080/ &'
alias vs="open_visual_studio"
alias cs='~/.scripts/code_search.sh'
alias tip="echo 'If applied, this commit will'"
alias todo='echo "$@" >> ~/notes/todo.md'