#!/bin/sh
# https://1password.com/downloads/linux/

repo="$(mktemp -d)/1password"

curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
git clone https://aur.archlinux.org/1password.git --depth 1 "${repo}"

cd "${repo}"
makepkg -si
rm -rf "${repo}"
