#!/bin/bash
## Ledger Agent, <https://github.com/fdv/ledger-agent-add>
## NOTE: Unable to get this to install on WSL2 (Debian)

set -e

## Requires python3, pip3, libusb
sudo apt install python3 python3-pip libusb-1.0-0-dev

pip3 install ledger_agent
