#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset


bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

# Install python dependencies
echo "Install python dependencies"
pip install codespell flake8 isort black
