#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail


# sudo pacman -S base-devel cmake unzip ninja tree-sitter curl

repository="git@github.com:neovim/neovim.git"
neovim_source="$REPOS/neovim/neovim"

if [ -d "$neovim_source" ]; then
  cd "$neovim_source"
  echo "Neovim already cloned. Update: $neovim_source"
  git pull
else
  git clone $repository $neovim_source
fi

cd $neovim_source
make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX="$HOME/.local" install
