#!/usr/bin/env bash
# Get secret from AWS Secret Manager

set -o errexit
set -o nounset
set -o pipefail

secret_id="$1"
arn=$(aws secretsmanager describe-secret --secret-id $secret_id | jq -r ".ARN")
aws secretsmanager get-secret-value --secret-id $arn | jq -r ".SecretString | fromjson"
