#!/bin/sh
# Adds package to $INSTALL/arch

package=$1
[ -z "$(pacman -Ss "${package}")" ] && echo "${package} does not exist." && exit 1;

arch_package_file="${INSTALL}/arch/packages"
echo "${package}" >> "${arch_package_file}"
echo "${package} added to ${arch_package_file}"

read -p "Install packages? [y,n]? " install

if [[ ! $install =~ ^[Yy] ]]; then
  exit
fi

arch-install
