#!/bin/sh
# Adds package to $INSTALL/arch

package=$1
[ -z "$(pacman -Ss "${package}")" ] && echo "${package} does not exist." && exit 1;

echo "${package}" >> "${INSTALL}/arch"
echo "${package} added to ${INSTALL}/arch"

read -p "Install packages? [y,n]? " install

if [[ ! $install =~ ^[Yy] ]]; then
  exit
fi

arch-install
