#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Usage: audio <sink>
# Sinks: headphones, speakers
# Default: headphones
sink_cmd="${1:-headphones}"

HEADHPONES_SINK="alsa_output.usb-Plantronics_Poly_Voyager_Focus_2_Series_b12d6818571c43f19e42996af1f38ff9-00.analog-stereo"
SPEAKERS_SINK="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink"

if [[ "$sink_cmd" == "headphones" ]]; then
    pacmd "set-default-sink $HEADHPONES_SINK"
    exit 0
fi

if [[ "$sink_cmd" == "speakers" ]]; then
    pacmd "set-default-sink $SPEAKERS_SINK"
    exit 0
fi
