#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Monitoring - https://docs.anthropic.com/en/docs/claude-code/monitoring-usage
# Settings - https://docs.anthropic.com/en/docs/claude-code/settings
claude --permission-mode acceptEdits "$@"
