#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Setup - https://docs.anthropic.com/en/docs/claude-code/setup#local-installation
# Settings - https://docs.anthropic.com/en/docs/claude-code/settings
# Monitoring - https://docs.anthropic.com/en/docs/claude-code/monitoring-usage

exec "$HOME/.claude/local/node_modules/.bin/claude" --permission-mode acceptEdits "$@"
