#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# if no argument are passed
if [ $# -eq 0 ] ; then
  # copy from stdin
  xclip -rmlastnl -sel clip
fi

# if one argument is passed and is a file
if [ $# -eq 1 ] && [ -f $1 ] ; then
  # copy content of file
  xclip -sel clip "$1"
fi
