#!/usr/bin/env bash

# intern=eDP1
# extern=DP2

#if xrandr | grep "$extern disconnected"; then
    #xrandr --output $extern --off --output $intern --auto
    # xrandr --output "$extern" --off --output "$intern" --auto
#else
    #xrandr --output $extern --left-of $intern --auto
    #xrandr --output $extern --output $intern --off --auto
    # xrandr --output "$intern" --off --output "$extern" --auto
#fi
# xrandr --output eDP1 --mode 3840x2400 --output DP3 --mode 2048x1080 --left-of eDP1
# xrandr --output DP2 --auto --right-of eDP1

samsung() {
  xrandr --output DP-2 --mode 5120x1440 --rate 120 --output HDMI-0 --off
}

tibber() {
  xrandr --output DP-3 --auto --above eDP-1
}

# if argument is equal to samsung
case "$1" in
    samsung)
        samsung
        ;;
    tibber)
        tibber
        ;;

    # logout)
    #     i3-msg exit
    #     ;;
    # suspend)
    #     lock && systemctl suspend
    #     ;;
    # hibernate)
    #     lock && systemctl hibernate
    #     ;;
    # reboot)
    #     systemctl reboot
    #     ;;
    # shutdown)
    #     systemctl poweroff
    #     ;;
    *)
        echo "Usage: $0 {samsung, tibber}"
        exit 2
esac
# if [ "$1" = "samsung" ]; then
#     xrandr --output DP-2 --mode 5120x1440 --rate 120
# fi
