#!/usr/bin/env python3
import sys


def main():
    # Read from stdin
    lines = [line.strip() for line in sys.stdin]

    # Find duplicated lines
    duplicates = set()
    for line in lines:
        if lines.count(line) > 1:
            duplicates.add(line)

    # Print duplicates
    for duplicate in duplicates:
        print(duplicate)

main()
