#!/bin/bash
set -e

## TODO: Add support for GitHub URL

usage="usage: clone <user/repository> <git-flags>"
[ -z "${REPOS}" ] && echo "REPOS not set" && exit 1;
[ -z "${1}" ] && echo "$usage" && exit 1;
## Check if $1 contains / 
[ "${1##*/*}" ] && echo "$usage" && exit 1;

## Split input "<user>/<repository>"
user=${1%/*}
repository=${1##*/}
flags="${*:2}"

path="${REPOS}/${user}/${repository}"
url="git@github.com:${user}/${repository}"
echo "${repository}:${url}" >> "${path}/.clone"
# git clone ${url} $path
git clone ${flags-} "${url}" "${path}"
echo "${path}"
