#!/bin/bash
set -e

# Remove string "hello" from beggining of argument

usage="usage: clone <user/repository> <git-flags>"
[ -z "${REPOS}" ] && echo "REPOS not set" && exit 1;
[ -z "${1}" ] && echo "$usage" && exit 1;

url="${1#https://github.com/}"

## Check if $1 contains / 
[ "${url##*/*}" ] && echo "$usage" && exit 1;

## Split input "<user>/<repository>"
user=${url%/*}
repository=${url##*/}
flags="${*:2}"

path="${REPOS}/${user}/${repository}"
if [ -d "${path}" ]; then
    echo "Repository already cloned"
    exit 1
fi
git_url="git@github.com:${user}/${repository}"
# git clone ${url} $path
git clone ${flags-} "${git_url}" "${path}"
echo "${repository}:${git_url}" >> "${REPOS}/${user}/.clone"
echo "${path}"
