#!/usr/bin/env python3
#
# Parse a github link containing line number
import sys

# examples:
# github_link=https://github.com/tibbercom/tibber-cron/blob/master/src/index.js#L41
# https://github.com/tibber/tibber-pyDemandResponse/blob/master/src/devices/fleet.py#L5
github_link = sys.argv[1]

part = github_link.split("/")
owner = part[3]
repo = part[4]
branch = part[6]
path = str.join("/", part[7:-1])
filename = part[-1].split("#")[0]
line_number = part[-1].split("#L")[1] if "#L" in part[-1] else ""

# print(f"org: {owner}")
# print(f"repo: {repo}")
# print(f"branch: {branch}")
# print(f"path: {path}")
# print(f"filename: {filename}")
# print(f"line number: {line_number}")

# API download link
API_URL = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}/{filename}"
print(API_URL)
