#!/usr/bin/env bash
set -o errexit
set -o pipefail

OPENAI_API_KEY=$(pass OpenAI/OPENAI_API_KEY)

help() {
  echo "Usage: gpt <command> <args>"
  echo "       gpt <command> --help"
  echo "       gpt --help"
  echo "       gpt commifg"
  echo "       gpt --version"
  echo ""
  echo "Commands:"
  echo "  help        Show this help message"
  echo "  version     Show the version of gpt"
}

commit() {
  if [ -z "$1" ]; then
    diff=$(git diff --cached)
  elif [ "$1" == "-" ]; then
    diff=$(cat)
  else
    echo "Usage: gpt commit [-]"
    return
  fi

  prompt="I want you to act like a git commit message writer. I will input a git diff and your job is to convert it into a useful commit message. Do not preface the commit with anything, use the present tense, return a complete sentence, and do not repeat yourself: $diff"
  prompt=$(echo -n "$prompt" | jq -sRr @uri)

  response=$(curl -s https://api.openai.com/v1/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d '{
    "model": "text-davinci-003",
    "prompt": "'"$prompt"'",
    "temperature": 0,
    "max_tokens": 60,
    "top_p": 1.0,
    "frequency_penalty": 0.0,
    "presence_penalty": 0.0
  }')

  echo "$response" | jq -r '.choices[0].text' | sed 's/%0A//g' | sed 's/Commit message: //g' | sed '/^$/d'
}

command="$1"

case "$command" in
  help)
    help
    ;;
  version)
    echo "0.1.0"
    ;;
  commit)
    shift
    commit "$@"
    ;;
  *)
    echo "Unknown command: $command"
    echo ""
    help
    exit 1
    ;;
esac
