#!/usr/bin/env python3

import argparse
import json
import logging
import os
import sys

import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

LOG = logging.getLogger(__name__)

logging.basicConfig(
    stream=sys.stdout,
    level=logging.INFO,
    format="%(message)s",
)


def debug(event, code=None, language=None):
    def create_message():
        message = f"{event}"

        if code:
            languages = {
                "python": "python",
                "py": "py",
                "json": "json",
                None: "",
            }

            message += f"\n```{languages[language]}\n{code}\n```"

        return message

    LOG.debug("%s", create_message())


def request_completion(request) -> str:
    debug("sending request", json.dumps(request, indent=1), "json")
    response = openai.Completion.create(**request)
    debug("response", json.dumps(response, indent=1), "json")

    return response.choices[0].text


def code_question(question):
    prompt = f"""
I am a highly intelligent python question answering bot. If you ask me a question about python or code in general, I will give you the answer. If you ask me a question that is nonsense, trickery, or has no clear answer, I will respond with "Unknown".

Q: How to get the name of the function in python?
A: In Python, you can get the name of a function by accessing the __name__ attribute of the function object. The __name__ attribute is a built-in attribute of all Python functions that contains the name of the function as a string.

Q: 
A: 

Q: 
A: 

Q: 
A: 

Q: 
A: 

Q: 
A: 

Q: How many squigs are in a bonk?
A: Unknown\n

Q: {question}
A: 
"""
    request = dict(
        model="text-davinci-003",
        prompt=prompt,
        temperature=0,
        max_tokens=100,
        top_p=1,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        stop=["\n"],
    )
    response_text = request_completion(request)
    print(response_text)

def question(question):
    prompt = f"""
I am a highly intelligent question answering bot. If you ask me a question that is rooted in truth, I will give you the answer. If you ask me a question that is nonsense, trickery, or has no clear answer, I will respond with "Unknown".

Q: What is human life expectancy in the United States?
A: Human life expectancy in the United States is 78 years.

Q: Who was president of the United States in 1955?
A: Dwight D. Eisenhower was president of the United States in 1955.

Q: Which party did he belong to?
A: He belonged to the Republican Party.

Q: What is the square root of banana?
A: Unknown

Q: How does a telescope work?
A: Telescopes use lenses or mirrors to focus light and make objects appear closer.

Q: Where were the 1992 Olympics held?
A: The 1992 Olympics were held in Barcelona, Spain.

Q: How many squigs are in a bonk?
A: Unknown\n

Q: {question}
A: 
"""
    request = dict(
        model="text-davinci-003",
        prompt=prompt,
        temperature=0,
        max_tokens=100,
        top_p=1,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        stop=["\n"],
    )
    response_text = request_completion(request)
    print(response_text)


def explain_code(code):
    STOP = '"""'

    prompt = f"""{code}{STOP}
Here is an explaination of the above code:"""

    request = dict(
        model="code-davinci-002",
        prompt=prompt,
        temperature=0,
        max_tokens=64,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        stop=['"""'],
    )
    response_text = request_completion(request)
    print(response_text)


# CLI application gpt
# Usage: gpt <command> [options]
# Commands:
#   code  Explain code
# Options:
#   -h, --help      Show this message and exit.
#   -v, --verbose   Show verbose output

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="GPT-3 CLI application")

    parser.add_argument("command", choices=["code", "question"], help="Command to run")
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Show verbose output"
    )
    args = parser.parse_args()

    if args.verbose:
        LOG.setLevel(logging.DEBUG)
        LOG.debug("Verbose output enabled")
        print("Verbose output enabled")

    subcommand = args.command

    LOG.debug("Executing subcommand: %s", subcommand)
    if subcommand == "code":
        explain_code(sys.stdin.read())
        exit(0)
    elif subcommand == "question":
        query = input("Q: ")
        question(query)
