#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

[[ -z "${SCRIPTS:-}" ]] && printf "SCRIPTS not set\n" >&2 && exit 1
[[ -z "${1:-}" ]] && printf "usage: %s <name>\n" "$0" >&2 && exit 1

path="${SCRIPTS}/${1}"

[[ ! -e "${path}" ]] && {
cat <<EOF > "${path}"
#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
EOF
chmod +x "${path}"
}

"${EDITOR:-vi}" +2 "${path}"
