#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

[ ! -n "${SCRIPTS}" ] && echo "SCRIPTS not set" && exit 1;
[ ! -n "${1}" ] && echo "usage: newscript <name>" && exit 1;

path="${SCRIPTS}/${1}"

if [ -e "${path}" ]; then
  exec $EDITOR "${path}"
  exit 0
fi

printf '#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
' > "${path}"
chmod +x "${path}"
exec vim +2 "${path}"
