#!/bin/sh

alias firefox='/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe'

# No arguments
if [ $# -eq 0 ] ; then
  # If no arguments try to open as github repository.
  github-open
  exit 0
fi

url="$@"
firefox -new-tab "${url}"
