#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# pr-body - Edit the body of a pull request
# Usage: pr-body [<body>]
# If no argument is passed, read the existing body and use it as input
# If one argument is passed as a string take that as body
# If data on stdin, use that as body
body=""
# If data on stdin, use that as body
if [ -p /dev/stdin ]; then
  body=$(cat)
fi
# If one argument is passed as a string take that as body
if [[ "$#" -eq 1 ]]; then
  body="$1"
fi
# If no argument is passed, read the existing body and use it as input
if [[ -z "$body" ]]; then
  body_file=$(mktemp --suffix=.md)
  gh pr view --json body -q .body > "$body_file"
  $EDITOR "$body_file"
  body=$(cat "$body_file")
fi

gh pr edit --body "${body}" && gh pr view --web
