#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Set stdin or argument "<title>" as input
title="${1:-$(cat)}"
# Make sure its only one argument in '"' or "'"
if [[ "$#" -gt 1 || "$title" == "" ]]; then
  echo "Usage: pr-title \"<title>\""
  exit 1
fi
echo "$title"
gh pr edit --title "${title}" && gh pr view --web
