#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

instructions="You are code reviewer. You will receive code or documentation that I would like you to review."
file="${1:-/dev/stdin}"

gpt -i "$instructions" "$file"
