#!/bin/sh

alias rider='/mnt/c/Program\ Files/JetBrains/JetBrains\ Rider\ 211.6432.4/bin/rider64.exe'

if [ $# -eq 0 ] ; then
  rider $(find . -name '*.sln') > /dev/null 2>&1 &
else
  rider $@ > /dev/null 2>&1 &
fi
