#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Session Note
# Take notes related to the current tmux-session name
if [[ -n $TMUX ]]; then
  current_session=$(tmux display-message -p '#S')
  $EDITOR "$NOTES/session-notes/${current_session}.md"
  cd "$NOTES"
  git add session-notes
  git commit -m "Update session notes for $current_session"
  git push
else
  echo "You are not in a tmux session."
fi
