#!/usr/bin/env bash
# Argument parser for session management

set -o errexit
set -o pipefail


usage() {
  echo "Usage: sessions [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -l, --list: List all the sessions"
  echo "  -s, --switch: Switch to a session"
  echo ""
  echo "Examples:"
  echo "  sessions -l"
  echo "  sessions -s"
  echo ""
  echo "Sessions:"
  tmux ls | awk -F: '{print $1}'
  echo ""
  echo "Environment variables:"
  exit 1
}

if [[ -z $1 ]]; then
  tmux ls | awk -F: '{print $1}'
fi

# -l, --list
if [[ "$1" == "-l" || "$1" == "--list" ]]; then
  tmux ls | awk -F: '{print $1}'
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
fi

# -s, --switch
if [[ "$1" == "-s" || "$1" == "--switch" ]]; then
  target=$(tmux ls | cut -d: -f1| fzf --reverse)
  [ -z "$target" ] && exit 1

  if [[ "$TMUX" ]]; then
    tmux switch-client -t "$target"
  else
    tmux attach-session -t "$target"
  fi
  exit
fi
