#!/usr/bin/env bash
# Attach to tmux sessions

set -o errexit
set -o pipefail

switch-session() {
  local target
  target=$(tmux ls | cut -d: -f1 | fzf --reverse)
  [ -z "$target" ] && exit 1;

  tmux switch -t "$target"
}

attach-to-session() {
  local target
  target=$(tmux ls | cut -d: -f1 | fzf --reverse)
  [ -z "$target" ] && exit 1;

  tmux attach-session -t "$target"
}

if [[ -n $TMUX ]]; then
  current_session=$(tmux display-message -p '#S')
  read -rp "Already in session '$current_session', switch? [y,n]? " switch_session
  if [[ ! $switch_session =~ ^[Yy] ]]; then
    # List session without switching
    tmux ls | cut -d: -f1
    exit
  else
    switch-session && exit;
  fi
fi

attach-to-session
