#!/usr/bin/env bash
set -o errexit
set -o pipefail

GIST_ID="$(pass GitHub/gist-tibber-todo)"

if [[ "$1" == "--web" ]]; then
  shift
  gh gist view "$GIST_ID" "$@" --web
  exit 0
fi

gh gist edit "$GIST_ID" "$@"
