#!/bin/bash
# urlencode <string>
usage="usage: url-encode <string>"
[ ! "$#" -ne 2 ] && echo "${usage}" && exit 1;
[ ! -n "${1}" ] && echo "${usage}" && exit 1;

length="${#1}"
for (( i = 0; i < length; i++ )); do
    c="${1:i:1}"
    case $c in
        [a-zA-Z0-9.~_-]) printf "$c" ;;
        *) printf '%s' "$c" | xxd -p -c1 |
               while read c; do printf '%%%s' "$c"; done ;;
    esac
done
