#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

ssid=${1-$(nmcli -t -f SSID dev wifi list | sort -u | awk "NF"| fzf)}

n=0
until [ "$n" -ge 5 ]
do
  nmcli dev wifi connect "$ssid" && break
  n=$((n+1))
  sleep 3
done

