#!/bin/bash

SSID="Caspar iPhone"

# nmcli
# CONNECT_CMD="nmcli dev wifi connect $SSID"
# SCAN_CMD="nmcli dev wifi rescan"

# iwctl
CONNECT_CMD="iwctl station wlan0 connect \"$SSID\""
SCAN_CMD="iwctl station wlan0 scan"
echo -n "Trying to connect to $SSID"

n=0
until [ "$n" -ge 10 ]
do
  echo -n "."
  eval $CONNECT_CMD 2>/dev/null && break
  eval $SCAN_CMD
  n=$((n+1))
  sleep 3
done
echo ""
