#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Check that network manager is running
if ! systemctl is-active --quiet NetworkManager; then
    echo "NetworkManager is not running. Please start it first."
    exit 1
fi

nmcli device wifi list
